<?php

/**
 * This module handles study plan form
 *
 */

/**
 * Implementation of hook_form_alter().
 */
function study_plan_form_form_alter(&$form, &$form_state, $form_id) 
{
	$study_plan_form_id = "webform_client_form_506";

  switch($form_id) 
  {
		case "$study_plan_form_id":
			$form['actions']['calculate_button'] = array(
  			'#type' => 'submit',
  			'#value' => t('Calculate study plan'),
			);

			$form['actions']['submit']['#value'] = 'Submit to Arts student centre';

			$form['#validate'][] = '_study_plan_form_validate';
			
		  break;
  }
}


function study_plan_form_tokens_alter(array &$replacements, array $context) {
  if ($context['type'] == 'submission' && !empty($context['data']['webform-submission'])) {
    $submission_obj = $context['data']['webform-submission'];
    //$node = $context['data']['node'] ? $context['data']['node'] : node_load($submission->nid);
		$submission_data = $submission_obj->data;
		$new_submission_data = _translate_submission_data_key($submission_data);
	
		// Total points
		$total_points = 0;
	
		// Level 1 arts studies	
		$form_key_array = array(
			"arts_foundation_subject",
			"arts_foundation_discipline",
			"discipline_1",
			"discipline_2",
			"discipline_3",
			"discipline_4"
		);
		$level_1_arts_studies_points = _calculate_subject_points($new_submission_data, $form_key_array);
	
		// First major
		$form_key_array = array(
			"major_1_level_1_subject_1",
			"major_1_level_1_subject_2",
			"major_1_level_1_subject_3",
			
			"major_1_level_2_subject_1",
			"major_1_level_2_subject_2",
			"major_1_level_2_subject_3",
			
			"major_1_level_3_subject_1",
			"major_1_level_3_subject_2",
			"major_1_level_3_subject_3"
		);
		$first_major_points = _calculate_subject_points($new_submission_data, $form_key_array);
	
		// Second major
		$form_key_array = array(
			"major_2_level_1_subject_1",
			"major_2_level_1_subject_2",
			
			"major_2_level_2_subject_1",
			"major_2_level_2_subject_2",
			"major_2_level_2_subject_3",
			
			"major_2_level_3_subject_1",
			"major_2_level_3_subject_2",
			"major_2_level_3_subject_3"
		);
		$second_major_points = _calculate_subject_points($new_submission_data, $form_key_array);
	
		// Breadth subject
		$form_key_array = array(
			"breadth_subject_1",
			"breadth_subject_2",
			"breadth_subject_3",
			"breadth_subject_4",
			"breadth_subject_5",
			"breadth_subject_6",
			
			"half_subject_1",
			"half_subject_2",
			"half_subject_3",
			"half_subject_4",
			"half_subject_5",
			"half_subject_6"
		);
		$breadth_points = _calculate_subject_points($new_submission_data, $form_key_array);

		// Total points
		$total_points = 
			$level_1_arts_studies_points +
			$first_major_points + 
			$second_major_points +
			$breadth_points;

    
    if(isset($context['data']['node']))
    {
    	$node = $context['data']['node'];
    
	  	// Complete a study plan check form
	  	if($node->nid == 506)
	  	{
	  	
	  		// Points
	  		$index = "[submission:values:level_1_arts_studies_points:nolabel]";
	  		$replacements[$index] = $level_1_arts_studies_points;
	  		
	  		$index = "[submission:values:first_major_total_points:nolabel]";
	  		$replacements[$index] = $first_major_points;
	  		
	  		$index = "[submission:values:second_major_total_points:nolabel]";
	  		$replacements[$index] = $second_major_points;
	  		 
	  		$index = "[submission:values:breadth_total_points:nolabel]";
	  		$replacements[$index] = $breadth_points;
	  		 
	  		$index = "[submission:values:total_points:nolabel]";
	  		$replacements[$index] = $total_points;
	  		 
	  	}
		  
    }
  }
}


/**
 * Additional validation handler for the Get Started form.
 */
function _study_plan_form_validate($form, &$form_state) 
{
  if($form_state['clicked_button']['#value'] == 'Calculate study plan') 
  {
    $submitted_array = $form_state['values']['submitted'];
    
    if(count($submitted_array) > 0)
    {
    	
    	$total_points = 0;
    	foreach($submitted_array as $item)
    	{
    		//
    		$array = explode("--", $item);
    		$point = (float)$array[2];
    		$total_points = $total_points + $point;
    	}
    	
    }
    
  	$message = "total: $total_points";
    drupal_set_message($message);
  }
}


function _translate_submission_data_key($submission_data)
{
	$array = array();
	foreach($submission_data as $key => $value)
	{
		$new_key = _translate_numeric_key_to_field_key($key);
		$array[$new_key] = $value[0];
	}

	return $array;
}


function _translate_numeric_key_to_field_key($key)
{
	$result = db_select('webform_component', 'com')
    ->fields('com', array("form_key"))
    ->condition('cid', $key, '=')
    ->range(0, 1)
    ->execute()
    ->fetchField();
	
	return $result;
}


function _calculate_subject_points($data, $form_key_array)
{
	$total_points = 0;
	
	foreach($form_key_array as $form_key)
	{
		$tmp_point = _get_single_subject_point($data[$form_key]);
		$total_points = $total_points + $tmp_point;	
	}
	
	return $total_points;
}


function _get_single_subject_point($item)
{
	$component_num = 3;
	
	// e.g. $item == MULT1--Arts Foundation Subject--12.5
	$array = explode("--", $item);
	
	if(count($array) == $component_num)
	{
		$point = $array[2];
	}
	else
	{
		$point = 0;
	}
	
	return (float)$point;
}

